CarletonURocketry/hybrid-engine-ui

hybrid-engine-ui.pyproject
packet_spec.py
widget.py

Closes #6 
This PR creates dataclasses of each of the telemetry packets. It also fixes a bug that would keep a TCP connection open if the window was closed.

Implement packet spec and handle TCP connection when closing window

---

packet_spec.py
widget.py

I have completed the parser and demultiplexing data. However, in the timer portion  that keep only 30s recent data, I'm not sure that I implemented that part right. Since there is some lag in running. But for parsing data, everything is working. If you want to test just run pad server on another shell and connect to it.

Parse data

---

form.ui
rc_resources.py
ui_form.py
widget.py

Added actuator states to the ui, removed the stop/start sim button, and made more room for the output log. More design stuff can be done (ex. making closed/open text red/green respectively, maybe adding unique labels if valves aren't in use) but it is good for now.

Actuator states

---

form.ui
ui_form.py
widget.py

Closes #21 
Scans network interfaces on startup and populates drop-down menu with interface IP addresses. If address is selected from drop-down, that address will be used to join the multicast group.

Add network interface selector

---

.gitignore
form.ui
packet_spec.py
ui_form.py
widget.py

This will write all datagram to a file with filename be the current date and .dump extension.
It will write in raw bytes, and read according just like when we receive an packet

Add recording data and read from previous data

---

form.ui
rc_resources.py
ui_form.py
widget.py

This PR changes the default graph colors to white mode as it will reduce glare when used irl.

Change graph colors

---

form.ui
ui_form.py
widget.py

Closes #32 
Partially works on #36, #37, #34 
This PR adds a separate tab for all ip/serial/graph related configuration options

Add config tab

---

main_window/data_handlers.py
main_window/logging.py
main_window/main_window.py
main_window/recording_and_playback.py
main_window/udp.py
main_window/ui/form.ui
main_window/ui/ui_form.py

This PR adds logs actuator states to the log output whenever the actuator states update

Log actuator states

---

data_conversions.py
main_window/data_handlers.py
main_window/main_window.py
main_window/serial.py
main_window/udp.py
main_window/ui/pid_window.ui
main_window/ui/ui_pid_window.py

This PR moves lines regarding UI updates into functions within the MainWindow class

Organize UI updates

---

config.json
main_window/data_handlers.py
main_window/main_window.py
main_window/serial.py
packet_spec.py

Closes #53 
This PR adds functionality to allow for the status field on the serial data packet to be properly parsed and update corresponding valves appropriately on the UI

Parse status int from serial connection

---

.gitignore
Hybrid Engine UI.spec
README.md

This PR adds the spec file that can be used to create an executable of the hybrid engine ui

Add files for pyinstaller

---

data_conversions.py
main_window/main_window.py
main_window/serial.py
packet_spec.py

This PR adds new sensors read from serial m2 and t3

Add new serial sensors

---

main_window/data_handlers.py
main_window/main_window.py

Closes #70 
This PR adds support for two additional pressure sensors, corresponding to the actual system

Add 5th and 6th pressure sensors and appropriate labeling

---

README.md
data_conversions.py
main_window/data_handlers.py
main_window/logging.py
main_window/main_window.py
main_window/serial.py
main_window/udp.py
packet_spec.py

add units and increase the line

---

main_window/data_handlers.py
main_window/main_window.py

Fix sensor ids

---

main_window/ui/form.ui
main_window/ui/ui_form.py

Clarify recording button label

---

.gitignore
main_window/csv_writer.py
main_window/main_window.py
main_window/recording_and_playback.py
main_window/serial.py
main_window/udp.py
packet_spec.py

Closes #88 
This PR add functionality for auto-logging of arming, valve and continuity states

Valve state csv

---

main_window/main_window.py

This PR fixes continuity not being logged in the data csv

Fix continuity not being logged

---

main_window/data_handlers.py

See PR title, makes it easier to tell if circuit is continuous or not.

Change continuity labels to either continous or not continuous

---

main_window/data_handlers.py
main_window/main_window.py

This PR cleans up the MainWindow class a bit by moving plot initialization to a function in stead of the init function. It also fixes a bug where disconnecting from UDP wouldn't set the arming state back to N/A and makes logs a little less verbose. CSV logs are still pretty messy but that may or may not get fixed later.

Organize applicaition a bit

---

README.md
config.json
main.py
main_window/__init__.py
main_window/config.py
main_window/csv_writer.py
main_window/data_handlers.py
main_window/labels.py
main_window/logging.py
main_window/main_window.py
main_window/plot_info.py
main_window/recording_and_playback.py
main_window/telem_vis_manager.py
main_window/timer_controller.py
main_window/udp.py
main_window/ui_manager.py

Closes #118 
Closes #112 
This massive PR refactors all core functionality to be included not via global functions in modules but as classes separated into their own responsibilities. As such, many new classes were introduced to make the codebase more approachable and understandable. Documentation was also written for all of the new classes and support has been temporarily removed for serial and recording and playback of raw data NOT CSV DATA. The latter should be re implemented.

Signals slots refactor

---

main_window/main_window.py
main_window/modules/__init__.py
main_window/modules/analysis.py
main_window/modules/recording_and_playback.py
main_window/modules/udp.py
main_window/modules/ui_manager.py
main_window/ui/form.ui
main_window/ui/ui_form.py

This PR adds a new tab to the hybrid engine UI meant for analyzing CSVs. This was added to make post-analysis of tests easier to conduct.

Add analysis tab
